# Chapter 5 


# Introduction to Numpy  


## Installation of numpy, scipy and pandas 


In [148]:
!pip install -q numpy 

In [149]:
def array_properties(a):
    print("a = \n", a)
    print("dim = ", a.ndim)
    print("shape = ", a.shape)
    print("datatype = ", a.dtype)
    print("size = ", a.size)
    print()

## Creating array  


In [150]:
import numpy as np

a = np.array([1, 2, 3])

print(a)
print()
print("a = \n", a)
print("dim = ", a.ndim)
print("shape = ", a.shape)
print("datatype = ", a.dtype)
print("size = ", a.size)
print()

[1 2 3]

a = 
 [1 2 3]
dim =  1
shape =  (3,)
datatype =  int32
size =  3



In [151]:
import numpy as np

a_3x3 = np.array([[1, 1, 1], [2, 2, 2], [3, 3, 3]])
array_properties(a_3x3)

a = 
 [[1 1 1]
 [2 2 2]
 [3 3 3]]
dim =  2
shape =  (3, 3)
datatype =  int32
size =  9



In [152]:
import numpy as np

seq_a = np.arange(1, 10)

array_properties(seq_a)

a = 
 [1 2 3 4 5 6 7 8 9]
dim =  1
shape =  (9,)
datatype =  int32
size =  9



In [153]:
import numpy as np

seq_a2 = np.linspace(1, 10, 15)

array_properties(seq_a2)

a = 
 [ 1.          1.64285714  2.28571429  2.92857143  3.57142857  4.21428571
  4.85714286  5.5         6.14285714  6.78571429  7.42857143  8.07142857
  8.71428571  9.35714286 10.        ]
dim =  1
shape =  (15,)
datatype =  float64
size =  15



In [154]:
import numpy as np

zeros_arr = np.zeros((2, 4))

array_properties(zeros_arr)

a = 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
dim =  2
shape =  (2, 4)
datatype =  float64
size =  8



In [155]:
import numpy as np

ones_arr = np.ones((4, 2))

array_properties(ones_arr)

a = 
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
dim =  2
shape =  (4, 2)
datatype =  float64
size =  8



In [156]:
import numpy as np

emp_arr = np.empty((4, 4))

array_properties(emp_arr)

a = 
 [[6.23042070e-307 4.67296746e-307 1.69121096e-306 1.20161526e-306]
 [8.34441742e-308 1.78022342e-306 6.23058028e-307 9.79107872e-307]
 [6.89807188e-307 7.56594375e-307 6.23060065e-307 1.78021527e-306]
 [8.34454050e-308 1.11261027e-306 1.15706896e-306 1.33512173e-306]]
dim =  2
shape =  (4, 4)
datatype =  float64
size =  16



In [157]:
import numpy as np

a1 = np.arange(1, 13)
array_properties(a1)

a2 = np.reshape(a1, (3, 4))
array_properties(a2)

a = 
 [ 1  2  3  4  5  6  7  8  9 10 11 12]
dim =  1
shape =  (12,)
datatype =  int32
size =  12

a = 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
dim =  2
shape =  (3, 4)
datatype =  int32
size =  12



In [158]:
import numpy as np

a1 = np.arange(1, 13, 1.5)
array_properties(a1)

a2 = np.reshape(a1, (4, -1))
array_properties(a2)

a = 
 [ 1.   2.5  4.   5.5  7.   8.5 10.  11.5]
dim =  1
shape =  (8,)
datatype =  float64
size =  8

a = 
 [[ 1.   2.5]
 [ 4.   5.5]
 [ 7.   8.5]
 [10.  11.5]]
dim =  2
shape =  (4, 2)
datatype =  float64
size =  8



In [159]:
import numpy as np

a1 = np.linspace(1, 10, 15).reshape(5, -1)

array_properties(a1)

a = 
 [[ 1.          1.64285714  2.28571429]
 [ 2.92857143  3.57142857  4.21428571]
 [ 4.85714286  5.5         6.14285714]
 [ 6.78571429  7.42857143  8.07142857]
 [ 8.71428571  9.35714286 10.        ]]
dim =  2
shape =  (5, 3)
datatype =  float64
size =  15



In [160]:
import numpy as np

a1 = np.random.rand(4, 5)

array_properties(a1)

a = 
 [[0.50377423 0.80317321 0.37154941 0.92567008 0.48195141]
 [0.64798226 0.71822461 0.07775472 0.78497945 0.94094523]
 [0.07913996 0.51280079 0.60642831 0.12277186 0.35259713]
 [0.13880567 0.30081944 0.90185817 0.07781897 0.29703805]]
dim =  2
shape =  (4, 5)
datatype =  float64
size =  20



In [161]:
import numpy as np

a1 = np.random.randint(0, 10, (4,5))

array_properties(a1)

a = 
 [[8 4 1 0 5]
 [6 0 2 1 5]
 [9 9 9 5 1]
 [6 1 0 4 6]]
dim =  2
shape =  (4, 5)
datatype =  int32
size =  20



## Accessing an array element






### 1 D Array


In [162]:
import numpy as np

a1 = np.arange(1, 13)
array_properties(a1)


a = 
 [ 1  2  3  4  5  6  7  8  9 10 11 12]
dim =  1
shape =  (12,)
datatype =  int32
size =  12



In [163]:
print('first: ', a1[0])
print('second: ', a1[1])
print('third: ', a1[3])


first:  1
second:  2
third:  4


In [164]:
print('ninth: ', a1[9-1])
print('last: ', a1[11])
print('last: ', a1[-1])


ninth:  9
last:  12
last:  12


In [165]:
print('index 0 to 4: ', a1[0:4])


index 0 to 4:  [1 2 3 4]


In [166]:
print('index 0 to 4: ', a1[:4])


index 0 to 4:  [1 2 3 4]


In [167]:
print('index 3 to 6: ', a1[3:6])


index 3 to 6:  [4 5 6]


In [168]:
print('index  0 to 10: ', a1[0:10])
print('index  0 to 10: ', a1[:10])


index  0 to 10:  [ 1  2  3  4  5  6  7  8  9 10]
index  0 to 10:  [ 1  2  3  4  5  6  7  8  9 10]


In [169]:
print('index 3 to last: ', a1[3:12])
print('index 3 to last: ', a1[3:])


index 3 to last:  [ 4  5  6  7  8  9 10 11 12]
index 3 to last:  [ 4  5  6  7  8  9 10 11 12]


In [170]:

print('index 3 to second to the last: ', a1[3:-1])


index 3 to second to the last:  [ 4  5  6  7  8  9 10 11]


In [171]:
print('last 2 numbers: ', a1[10:])
print('last 2 numbers: ', a1[-2:])


last 2 numbers:  [11 12]
last 2 numbers:  [11 12]


In [172]:
print('odd positions: ', a1[0::2])


odd positions:  [ 1  3  5  7  9 11]


In [173]:
print('even positions: ', a1[1::2])


even positions:  [ 2  4  6  8 10 12]


In [189]:
import numpy as np

N = 12
a1 = np.arange(N+1)

array_properties(a1)


a = 
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12]
dim =  1
shape =  (13,)
datatype =  int32
size =  13



In [192]:

for i in range(N+1):
    print(f'{i}: {a1[i]}')

0: 0
1: 1
2: 2
3: 3
4: 4
5: 5
6: 6
7: 7
8: 8
9: 9
10: 10
11: 11
12: 12


### 2 D Array


In [174]:
import numpy as np

a1 = np.arange(1, 17)

a2 = np.resize(a1, (4,4))
array_properties(a2)


a = 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
dim =  2
shape =  (4, 4)
datatype =  int32
size =  16



In [175]:
print('Element in row=1, column=1: ', a2[0,0])
print('Element in row=3, column=1: ', a2[2,0])
print('Element in row=2, column=3: ', a2[1,2])


Element in row=1, column=1:  1
Element in row=3, column=1:  9
Element in row=2, column=3:  7


In [176]:
array_properties(a2)

# row & index
row = 1
i = row - 1
# column & index
col = 2
j = col - 1

print(f'Element in row={row}, column={col}: ', a2[i,j])


a = 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
dim =  2
shape =  (4, 4)
datatype =  int32
size =  16

Element in row=1, column=2:  2


In [177]:
print(f'Elements in row= 2: ', a2[1,:])


Elements in row= 2:  [5 6 7 8]


In [178]:
print(f'Elements in col= 2: ', a2[:,1])


Elements in col= 2:  [ 2  6 10 14]


In [179]:
print(f'Elements in rows= 1 to 3 and columns= 2 to 4: \n', a2[0:3,1:3])
print()
print(f'Elements in row index= 0 to 2 and column index= 1 to 2: \n', a2[0:3,1:3])


Elements in rows= 1 to 3 and columns= 2 to 4: 
 [[ 2  3]
 [ 6  7]
 [10 11]]

Elements in row index= 0 to 2 and column index= 1 to 2: 
 [[ 2  3]
 [ 6  7]
 [10 11]]


In [206]:
array_properties(a2)

rows, columns = a2.shape
for i in range(rows):
    for j in range(columns):
        print(f'{i},{j}: {a2[i,j]}', end=', ')
    print()

print()

rows, columns = a2.shape
for i in range(rows):
    for j in range(columns):
        print(a2[i,j], end=', ')
    print()

a = 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
dim =  2
shape =  (4, 4)
datatype =  int32
size =  16

0,0: 1, 0,1: 2, 0,2: 3, 0,3: 4, 
1,0: 5, 1,1: 6, 1,2: 7, 1,3: 8, 
2,0: 9, 2,1: 10, 2,2: 11, 2,3: 12, 
3,0: 13, 3,1: 14, 3,2: 15, 3,3: 16, 

1, 2, 3, 4, 
5, 6, 7, 8, 
9, 10, 11, 12, 
13, 14, 15, 16, 


### 3D Array

In [180]:
import numpy as np

a3 = np.arange(1, 9).reshape((2,2,2))
array_properties(a3)


a = 
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
dim =  3
shape =  (2, 2, 2)
datatype =  int32
size =  8



In [207]:

print(a3[0,1,1])
print(a3[0,1,:])
print(a3[0,:,1])
print(a3[:,1,1])


4
[3 4]
[2 4]
[4 8]


In [208]:

a3D = np.array([
    [
        [111,112,113],
        [121,122,123],
    ],
    [
        [211,212,213],
        [221,222,223],
    ]
])

array_properties(a3D)


a = 
 [[[111 112 113]
  [121 122 123]]

 [[211 212 213]
  [221 222 223]]]
dim =  3
shape =  (2, 2, 3)
datatype =  int32
size =  12



In [209]:
print('Element 1,2,2: ', a3D[0,1,1])

Element 1,2,2:  122


In [210]:
array_properties(a3)

rows_3d, rows, columns = a3.shape
for i in range(rows_3d):
    for j in range(rows):
        for k in range(columns):
            print(f'{i},{j},{k}: {a3[i,j,k]}', end=', ')
        print()
    print()

print()

rows_3d, rows, columns = a3.shape
for i in range(rows_3d):
    for j in range(rows):
        for k in range(columns):
            print(a3[i,j,k], end=', ')
        print()
    print()

a = 
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
dim =  3
shape =  (2, 2, 2)
datatype =  int32
size =  8

0,0,0: 1, 0,0,1: 2, 
0,1,0: 3, 0,1,1: 4, 

1,0,0: 5, 1,0,1: 6, 
1,1,0: 7, 1,1,1: 8, 


1, 2, 
3, 4, 

5, 6, 
7, 8, 



## Changing Array Element

In [225]:
import numpy as np

a1 = np.arange(9)
array_properties(a1)


print('Third element: ', a1[2])

a1[2] = a1[2] ** 2
print('Third element squared: ', a1[2])


a = 
 [0 1 2 3 4 5 6 7 8]
dim =  1
shape =  (9,)
datatype =  int32
size =  9

Third element:  2
Third element squared:  4


In [238]:
import numpy as np

a2 = np.arange(1,10).reshape(3,3)
array_properties(a2)


print('2nd row, 2nd column element: ', a2[1,1])
a2[1,1] = a2[1,1] ** 2
print('2nd row, 2nd column element squared: ', a2[1,1])

print(a2)


a = 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
dim =  2
shape =  (3, 3)
datatype =  int32
size =  9

2nd row, 2nd column element:  5
2nd row, 2nd column element squared:  25
[[ 1  2  3]
 [ 4 25  6]
 [ 7  8  9]]


In [239]:

print('Third row: ', a2[2])
a2[2] = a2[2] * 2
print('Third row doubled: ', a2[2])

print(a2)


Third row:  [7 8 9]
Third row doubled:  [14 16 18]
[[ 1  2  3]
 [ 4 25  6]
 [14 16 18]]


In [240]:

print('First row: ', a2[0])
a2[0] = a2[0] + a2[1]
print('First row increased by second row: ', a2[0])

print(a2)


First row:  [1 2 3]
First row increased by second row:  [ 5 27  9]
[[ 5 27  9]
 [ 4 25  6]
 [14 16 18]]


In [241]:

print('Second row: ', a2[1])
a2[1] = a2[1] - a2[2]
print('Second row decreased by third row: ', a2[1])

print(a2)


Second row:  [ 4 25  6]
Second row decreased by third row:  [-10   9 -12]
[[  5  27   9]
 [-10   9 -12]
 [ 14  16  18]]
