# Chapter 5 


# Introduction to Numpy  


In [74]:
!pip install -q numpy 

Numpy mean numerical python. 
It is use for numerical operation and manipulation. Especially in array or matrix.

| 1 | 2 | 3 |
| --- | --- | ---|
| 4 | 5 | 6 |
| 7 | 8 | 9 |

order 3 x 3 


In [4]:
# import package numpy and give it an alias np
import numpy as np

a = np.array(
    [
        [1,2,3],
        [4,5,6],
        [7,8,9]
    ]
)

print(a)

print("dim = ", a.ndim)
print("shape = ", a.shape)
print("datatype = ", a.dtype)
print("size = ", a.size)
print()


[[1 2 3]
 [4 5 6]
 [7 8 9]]
dim =  2
shape =  (3, 3)
datatype =  int32
size =  9



In [5]:
alist = [
        [1,2,3],
        [4,5,6],
        [7,8,9]
    ]

print(alist)
print(len(alist))
# print(size(alist))
# print(shape(alist))

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
3


In [6]:
print(type(a))

<class 'numpy.ndarray'>


In [7]:
print(type(alist))

<class 'list'>


In [8]:
import numpy as np

blist = [31, 32, 33]
b = np.array(blist)

print(blist)
print()
print(b)
print("dim = ", b.ndim)
print("shape = ", b.shape)
print("datatype = ", b.dtype)
print("size = ", b.size)
print()

[31, 32, 33]

[31 32 33]
dim =  1
shape =  (3,)
datatype =  int32
size =  3



In [9]:
import numpy as np

clist = [1, 'Tue', 3, 'Wed']
c = np.array(clist)

print(clist)
print()
print(c)
print("dim = ", c.ndim)
print("shape = ", c.shape)
print("datatype = ", c.dtype)
print("size = ", c.size)
print()

[1, 'Tue', 3, 'Wed']

['1' 'Tue' '3' 'Wed']
dim =  1
shape =  (4,)
datatype =  <U11
size =  4



Class activity

| 11 | 12 | 13 |
| --- | --- | ---|

order 1 x 3    
or row matrix

$$
\begin{pmatrix}
    11 & 12 & 13
\end{pmatrix}
$$

### Without specifying the datatype.

In [10]:
# import package numpy and give it an alias np
import numpy as np

a = np.array(
    [
        [11, 12, 13]
    ]
)

print(a)

print("dim = ", a.ndim)
print("shape = ", a.shape)
print("datatype = ", a.dtype)
print("size = ", a.size)
print()


[[11 12 13]]
dim =  2
shape =  (1, 3)
datatype =  int32
size =  3



### Specifying datatype int64

In [11]:
# import package numpy and give it an alias np
import numpy as np

a = np.array(
    [
        [11, 12, 13]
    ], dtype='int64'
)

print(a)

print("dim = ", a.ndim)
print("shape = ", a.shape)
print("datatype = ", a.dtype)
print("size = ", a.size)
print()


[[11 12 13]]
dim =  2
shape =  (1, 3)
datatype =  int64
size =  3



### Specifying datatype float

In [12]:
# import package numpy and give it an alias np
import numpy as np

a = np.array(
    [
        [11, 12, 13]
    ], dtype='float'
)

print(a)

print("dim = ", a.ndim)
print("shape = ", a.shape)
print("datatype = ", a.dtype)
print("size = ", a.size)
print()


[[11. 12. 13.]]
dim =  2
shape =  (1, 3)
datatype =  float64
size =  3



### Specifying datatype float32

In [13]:
# import package numpy and give it an alias np
import numpy as np

a = np.array(
    [
        [11, 12, 13]
    ], dtype='float32'
)

print(a)

print("dim = ", a.ndim)
print("shape = ", a.shape)
print("datatype = ", a.dtype)
print("size = ", a.size)
print()


[[11. 12. 13.]]
dim =  2
shape =  (1, 3)
datatype =  float32
size =  3



### float value

In [14]:
# import package numpy and give it an alias np
import numpy as np

a = np.array(
    [
        [11.0, 12.0, 13.0]
    ]
)

print(a)

print("dim = ", a.ndim)
print("shape = ", a.shape)
print("datatype = ", a.dtype)
print("size = ", a.size)
print()


[[11. 12. 13.]]
dim =  2
shape =  (1, 3)
datatype =  float64
size =  3



## Class activity

| 21 | 
|---|
| 22 | 
| 31 | 
| 0 | 

order 4 x 1   
or column matrix


$$
\begin{pmatrix}
    21  \\  
    22  \\  
    31  \\  
    0  \\  
\end{pmatrix}
$$

In [15]:
# import package numpy and give it an alias np
import numpy as np

a = np.array(
    [
        [21],
        [22],
        [31],
        [0],
    ], dtype='uint8'
)

print(a)

print("dim = ", a.ndim)
print("shape = ", a.shape)
print("datatype = ", a.dtype)
print("size = ", a.size)
print()


[[21]
 [22]
 [31]
 [ 0]]
dim =  2
shape =  (4, 1)
datatype =  uint8
size =  4



Minimum value in 8 bits

|7|6|5|4|3|2|1|0|
|---|---|---|---|---|---|---|---|
|0|0|0|0|0|0|0|0|

Maximum value in 8 bits

|7|6|5|4|3|2|1|0|
|---|---|---|---|---|---|---|---|
|1|1|1|1|1|1|1|1|

uint8 mean unsigned integer in 8 bits
min = 0
max = 255   

int8 mean signed integer in 8 bits
min = -128
max = 127

## Installation of numpy, scipy and pandas 


In [1]:
!pip install -q numpy 

In [2]:
def array_properties(a):
    print("a = \n", a)
    print("dim = ", a.ndim)
    print("shape = ", a.shape)
    print("datatype = ", a.dtype)
    print("size = ", a.size)
    print()

## Creating array  


In [3]:
import numpy as np

a = np.array([1, 2, 3])

print(a)
print()
print("a = \n", a)
print("dim = ", a.ndim)
print("shape = ", a.shape)
print("datatype = ", a.dtype)
print("size = ", a.size)
print()

[1 2 3]

a = 
 [1 2 3]
dim =  1
shape =  (3,)
datatype =  int32
size =  3



In [16]:
import numpy as np

a_3x3 = np.array([[1, 1, 1], [2, 2, 2], [3, 3, 3]])
array_properties(a_3x3)

a = 
 [[1 1 1]
 [2 2 2]
 [3 3 3]]
dim =  2
shape =  (3, 3)
datatype =  int32
size =  9



## arange 

integer array creation.

range used regularly in for loop

In [17]:
for n in range(10):
    print(n)

0
1
2
3
4
5
6
7
8
9


In [18]:
start = 1
stop = 10 + 1
for n in range(start,stop):
    print(n, end=', ')

1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 

In [19]:
start = 1
stop = 10 + 1
step = 2
for n in range(start, stop, step):
    print(n, end=', ')

1, 3, 5, 7, 9, 

In [20]:
import numpy as np

seq_a = np.arange(1, 10)

array_properties(seq_a)

a = 
 [1 2 3 4 5 6 7 8 9]
dim =  1
shape =  (9,)
datatype =  int32
size =  9



In [21]:
import numpy as np

ar10 = np.arange(10)

array_properties(ar10)

for n in ar10:
    print(n, end=' | ')

a = 
 [0 1 2 3 4 5 6 7 8 9]
dim =  1
shape =  (10,)
datatype =  int32
size =  10

0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 

In [22]:
start = 1
stop = 10 + 1
step = 2

ar10b = np.arange(start, stop, step)
array_properties(ar10b)

for n in ar10b:
    print(n, end=' | ')

a = 
 [1 3 5 7 9]
dim =  1
shape =  (5,)
datatype =  int32
size =  5

1 | 3 | 5 | 7 | 9 | 

In [23]:
start = 1
stop = 10 + 1
step = 2

ar10b = np.arange(start, stop, step)

ar10b = np.uint8(ar10b)
array_properties(ar10b)

for n in ar10b:
    print(n, end=' | ')

print()
print()

ar10b = np.float32(ar10b)
array_properties(ar10b)


a = 
 [1 3 5 7 9]
dim =  1
shape =  (5,)
datatype =  uint8
size =  5

1 | 3 | 5 | 7 | 9 | 

a = 
 [1. 3. 5. 7. 9.]
dim =  1
shape =  (5,)
datatype =  float32
size =  5



## Class Activity 

Create an array of integers [0, 5, 15, ..., 100]

## linspace 

create array of floating point value of a specific size.

In [24]:
import numpy as np

seq_a2 = np.linspace(1, 10, 15)

array_properties(seq_a2)

a = 
 [ 1.          1.64285714  2.28571429  2.92857143  3.57142857  4.21428571
  4.85714286  5.5         6.14285714  6.78571429  7.42857143  8.07142857
  8.71428571  9.35714286 10.        ]
dim =  1
shape =  (15,)
datatype =  float64
size =  15




|1|2|3|4|5|6|7|8|9|10|
|---|---|---|---|---|---|---|---|---|---|
|0|1|2|3|4|5|6|7|8|9|
|0|x|x|x|x|x|x|x|x|10|

0 --> 0   
1 --> x  
2 --> x  
9 --> 10

In [25]:
x = 10/9 * 9
x

10.0

In [26]:
import numpy as np

start = 0
stop = 10
size = 10

arls_0_10_10 = np.linspace(start, stop, size)

array_properties(arls_0_10_10)

a = 
 [ 0.          1.11111111  2.22222222  3.33333333  4.44444444  5.55555556
  6.66666667  7.77777778  8.88888889 10.        ]
dim =  1
shape =  (10,)
datatype =  float64
size =  10



In [27]:
import numpy as np

start = 0
stop = 10
size = 11

arls_0_10_11 = np.linspace(start, stop, size)

array_properties(arls_0_10_11)

a = 
 [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
dim =  1
shape =  (11,)
datatype =  float64
size =  11



## zeros

create array of zeros

In [28]:
import numpy as np

zer_10 = np.zeros((1,10))
array_properties(zer_10)

a = 
 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
dim =  2
shape =  (1, 10)
datatype =  float64
size =  10



In [29]:
import numpy as np

zer_10a = np.zeros((1,10), dtype='float32')
array_properties(zer_10a)

a = 
 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
dim =  2
shape =  (1, 10)
datatype =  float32
size =  10



In [30]:
import numpy as np

zer_10 = np.zeros((1,10), dtype=np.float32)
array_properties(zer_10)

a = 
 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
dim =  2
shape =  (1, 10)
datatype =  float32
size =  10



In [31]:
import numpy as np

zer_10c = np.zeros((1,10), dtype='int')
array_properties(zer_10c)

a = 
 [[0 0 0 0 0 0 0 0 0 0]]
dim =  2
shape =  (1, 10)
datatype =  int32
size =  10



In [32]:
import numpy as np

zer_10 = np.zeros((1,10), dtype=np.uint8)
array_properties(zer_10)

a = 
 [[0 0 0 0 0 0 0 0 0 0]]
dim =  2
shape =  (1, 10)
datatype =  uint8
size =  10



In [33]:
import numpy as np

zeros_arr = np.zeros((2, 4))

array_properties(zeros_arr)

a = 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
dim =  2
shape =  (2, 4)
datatype =  float64
size =  8



In [34]:
import numpy as np

zer_4_5_3 = np.zeros((4,5,3), dtype=np.uint8)
array_properties(zer_4_5_3)

a = 
 [[[0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
dim =  3
shape =  (4, 5, 3)
datatype =  uint8
size =  60



In [35]:
import numpy as np

zer_4_5_3_2 = np.zeros((4,5,3,2), dtype=np.uint8)
array_properties(zer_4_5_3_2)

a = 
 [[[[0 0]
   [0 0]
   [0 0]]

  [[0 0]
   [0 0]
   [0 0]]

  [[0 0]
   [0 0]
   [0 0]]

  [[0 0]
   [0 0]
   [0 0]]

  [[0 0]
   [0 0]
   [0 0]]]


 [[[0 0]
   [0 0]
   [0 0]]

  [[0 0]
   [0 0]
   [0 0]]

  [[0 0]
   [0 0]
   [0 0]]

  [[0 0]
   [0 0]
   [0 0]]

  [[0 0]
   [0 0]
   [0 0]]]


 [[[0 0]
   [0 0]
   [0 0]]

  [[0 0]
   [0 0]
   [0 0]]

  [[0 0]
   [0 0]
   [0 0]]

  [[0 0]
   [0 0]
   [0 0]]

  [[0 0]
   [0 0]
   [0 0]]]


 [[[0 0]
   [0 0]
   [0 0]]

  [[0 0]
   [0 0]
   [0 0]]

  [[0 0]
   [0 0]
   [0 0]]

  [[0 0]
   [0 0]
   [0 0]]

  [[0 0]
   [0 0]
   [0 0]]]]
dim =  4
shape =  (4, 5, 3, 2)
datatype =  uint8
size =  120



## ones

Create array of ones

In [75]:
import numpy as np

# specify the shape of the array in the `np.ones` function.
ones_arr = np.ones((4, 2))

array_properties(ones_arr)

a = 
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
dim =  2
shape =  (4, 2)
datatype =  float64
size =  8



In [76]:
import numpy as np

shape = (1,10)

ones_10 = np.ones(shape)

array_properties(ones_10)

a = 
 [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
dim =  2
shape =  (1, 10)
datatype =  float64
size =  10



In [77]:
import numpy as np

shape = (10,)

ones_10 = np.ones(shape)

array_properties(ones_10)

a = 
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
dim =  1
shape =  (10,)
datatype =  float64
size =  10



## Class Activity

Create an array of dim 3 filled with ones.

# Recap

1. Create array from list value
2. convert list to array.
3. Convert arrays of diffrent types (int32, int64, float64, float32, uint8, <U11)
4. Create array of zeros
5. Create array of ones

In [78]:
import numpy as np

emp_arr = np.empty((4, 4))

array_properties(emp_arr)

a = 
 [[4.67296746e-307 1.69121096e-306 1.20161526e-306 8.34441742e-308]
 [1.78022342e-306 6.23058028e-307 9.79107872e-307 6.89807188e-307]
 [7.56594375e-307 6.23060065e-307 1.78021527e-306 8.34454050e-308]
 [1.11261027e-306 1.15706896e-306 1.33512173e-306 1.33504432e-306]]
dim =  2
shape =  (4, 4)
datatype =  float64
size =  16



## Class Activity
Create empty array of 1x10

In [79]:
import numpy as np

emp_1x10 = np.empty((1, 10))

array_properties(emp_1x10)

a = 
 [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
dim =  2
shape =  (1, 10)
datatype =  float64
size =  10



## Reshape

Create an array of 1x10 then reshape to 2x5

In [83]:
import numpy as np

ar1x10 = np.arange(1, 11)
array_properties(ar1x10)

# reshape class method
ar2x5 = ar1x10.reshape((2,5))
array_properties(ar2x5)

# reshape function of np
ar2x5 = np.reshape(ar1x10, (2,5))
array_properties(ar2x5)

a = 
 [ 1  2  3  4  5  6  7  8  9 10]
dim =  1
shape =  (10,)
datatype =  int32
size =  10

a = 
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
dim =  2
shape =  (2, 5)
datatype =  int32
size =  10

a = 
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
dim =  2
shape =  (2, 5)
datatype =  int32
size =  10



In [85]:
import numpy as np

arls10 = np.linspace(10, 55, 10)
array_properties(arls10)

# reshape into wrong container
ar3x3 = ar1x10.reshape((3,3))
array_properties(ar3x3)

a = 
 [10. 15. 20. 25. 30. 35. 40. 45. 50. 55.]
dim =  1
shape =  (10,)
datatype =  float64
size =  10



ValueError: cannot reshape array of size 10 into shape (3,3)

In [87]:
import numpy as np

a1 = np.arange(1, 13)
array_properties(a1)

a2 = np.reshape(a1, (3, 4))
array_properties(a2)

a = 
 [ 1  2  3  4  5  6  7  8  9 10 11 12]
dim =  1
shape =  (12,)
datatype =  int32
size =  12

a = 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
dim =  2
shape =  (3, 4)
datatype =  int32
size =  12



Reshape knowing only one dim size.

In [89]:
import numpy as np

arls10 = np.linspace(10, 55, 10)
array_properties(arls10)

# reshape into 5xunknown
ar5x_ = ar1x10.reshape((5,-1))
array_properties(ar5x_)

# reshape into unknown x5
ar_x5 = ar1x10.reshape((-1,5))
array_properties(ar_x5)

a = 
 [10. 15. 20. 25. 30. 35. 40. 45. 50. 55.]
dim =  1
shape =  (10,)
datatype =  float64
size =  10

a = 
 [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
dim =  2
shape =  (5, 2)
datatype =  int32
size =  10

a = 
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
dim =  2
shape =  (2, 5)
datatype =  int32
size =  10



In [91]:
import numpy as np

arls10 = np.linspace(10, 55, 10)
array_properties(arls10)

# reshape into 3xunknown
ar3x_ = ar1x10.reshape((3,-1))
array_properties(ar3x_)

a = 
 [10. 15. 20. 25. 30. 35. 40. 45. 50. 55.]
dim =  1
shape =  (10,)
datatype =  float64
size =  10



ValueError: cannot reshape array of size 10 into shape (3,newaxis)

In [92]:
import numpy as np

a1 = np.arange(1, 13, 1.5)
array_properties(a1)

a2 = np.reshape(a1, (4, -1))
array_properties(a2)

a = 
 [ 1.   2.5  4.   5.5  7.   8.5 10.  11.5]
dim =  1
shape =  (8,)
datatype =  float64
size =  8

a = 
 [[ 1.   2.5]
 [ 4.   5.5]
 [ 7.   8.5]
 [10.  11.5]]
dim =  2
shape =  (4, 2)
datatype =  float64
size =  8



In [40]:
import numpy as np

a1 = np.linspace(1, 10, 15).reshape(5, -1)

array_properties(a1)

a = 
 [[ 1.          1.64285714  2.28571429]
 [ 2.92857143  3.57142857  4.21428571]
 [ 4.85714286  5.5         6.14285714]
 [ 6.78571429  7.42857143  8.07142857]
 [ 8.71428571  9.35714286 10.        ]]
dim =  2
shape =  (5, 3)
datatype =  float64
size =  15



## Class Activity

Create an array of shape 4x5 and reshape into 2x-1.

In [94]:
import numpy as np 

ar20 = np.linspace(1,21,20)
array_properties(ar20)

ar4x5 = ar20.reshape((4,5))
array_properties(ar4x5)

ar2x_ = ar4x5.reshape((2,-1))
array_properties(ar2x_)


a = 
 [ 1.          2.05263158  3.10526316  4.15789474  5.21052632  6.26315789
  7.31578947  8.36842105  9.42105263 10.47368421 11.52631579 12.57894737
 13.63157895 14.68421053 15.73684211 16.78947368 17.84210526 18.89473684
 19.94736842 21.        ]
dim =  1
shape =  (20,)
datatype =  float64
size =  20

a = 
 [[ 1.          2.05263158  3.10526316  4.15789474  5.21052632]
 [ 6.26315789  7.31578947  8.36842105  9.42105263 10.47368421]
 [11.52631579 12.57894737 13.63157895 14.68421053 15.73684211]
 [16.78947368 17.84210526 18.89473684 19.94736842 21.        ]]
dim =  2
shape =  (4, 5)
datatype =  float64
size =  20

a = 
 [[ 1.          2.05263158  3.10526316  4.15789474  5.21052632  6.26315789
   7.31578947  8.36842105  9.42105263 10.47368421]
 [11.52631579 12.57894737 13.63157895 14.68421053 15.73684211 16.78947368
  17.84210526 18.89473684 19.94736842 21.        ]]
dim =  2
shape =  (2, 10)
datatype =  float64
size =  20



## Class Activity

Create an array of 24 elements or size.
Reshape into multiples of 3 and 4 in row dimension.


In [ ]:
import numpy as np

# create a 1 dim array of size 24


# reshape into array o 3x-1


# reshape into array of 4x-1

## Class Activity 

Create an array of unsugned integer 8 bits of size 300 and reshape into (10,10,-1).

In [97]:
ar300 = np.arange(0,300,dtype='uint8')
print(ar300.shape)

ar10x10x_ = ar300.reshape((10,10,-1))
print(ar10x10x_.shape)


(300,)
(10, 10, 3)


In [101]:
# 10,-1,3
ar10x_x3 = ar300.reshape((10,-1,3))
print(ar10x_x3.shape)

# -1,10,3
ar_x10x3 = ar300.reshape((-1,10,3))
print(ar_x10x3.shape)





(10, 10, 3)
(10, 10, 3)


In [102]:
# -1,10,3
ar_x_x3 = ar300.reshape((-1,-1,3))
print(ar_x_x3.shape)

ValueError: can only specify one unknown dimension

## random

`rand` will geneartion random values between 0 - 1. It accepts the shape of the array to be created.

In [106]:
import numpy as np

# random array between 0-1 with shape (4,5)
a1 = np.random.rand(4, 5)

array_properties(a1)

a = 
 [[0.79355467 0.02398627 0.54799052 0.71533769 0.49971466]
 [0.6456805  0.19082646 0.58991645 0.0107417  0.53653781]
 [0.50731978 0.26904773 0.03908328 0.68412245 0.89308668]
 [0.93382234 0.10272734 0.67082097 0.19888379 0.72827832]]
dim =  2
shape =  (4, 5)
datatype =  float64
size =  20



Class Activity

Create an array with shape (3,7) of values between 0-1.

## randint  

Creates an array of integer.   
It accepts start, stop and shape.  
`randint(start, stop, shape)`

In [107]:
import numpy as np

a1 = np.random.randint(0, 10, (4,5))

array_properties(a1)

a = 
 [[2 1 5 8 3]
 [4 8 4 5 1]
 [9 8 4 5 2]
 [1 7 2 3 0]]
dim =  2
shape =  (4, 5)
datatype =  int32
size =  20



## Class Activity

Create an array of unsigned integer of 8 bits with shape (100, 100, 3) and filled with random integer values.

## Accessing an array element






### 1 D Array


In [108]:
import numpy as np

a1 = np.arange(1, 13)
array_properties(a1)


a = 
 [ 1  2  3  4  5  6  7  8  9 10 11 12]
dim =  1
shape =  (12,)
datatype =  int32
size =  12



|index|0|1|2|3|4|5|6|7|8|9|10|11|
|---|---|---|---|---|---|---|---|---|---|---|---|---|
|value|1|2|3|4|5|6|7|8|9|10|11|12|
|special index|-12|-11|-10|-9|-8|-7|-6|-5|-4|-3|-2|-1|

In [110]:
print('first: ', a1[0])
print('second: ', a1[1])
print('third: ', a1[2])


first:  1
second:  2
third:  3


In [45]:
print('ninth: ', a1[9-1])
print('last: ', a1[11])
print('last: ', a1[-1])


ninth:  9
last:  12
last:  12


In [112]:
# a1[istart:istop]
# stop or istop excluded
print('index 0 to 4: ', a1[0:4])


index 0 to 4:  [1 2 3 4]


In [113]:
# omitte the istart
print('index 0 to 4: ', a1[:4])


index 0 to 4:  [1 2 3 4]


In [48]:
print('index 3 to 6: ', a1[3:6])


index 3 to 6:  [4 5 6]


In [49]:
print('index  0 to 10: ', a1[0:10])
print('index  0 to 10: ', a1[:10])


index  0 to 10:  [ 1  2  3  4  5  6  7  8  9 10]
index  0 to 10:  [ 1  2  3  4  5  6  7  8  9 10]


In [50]:
# omitt istop equal last index
print('index 3 to last: ', a1[3:12])
print('index 3 to last: ', a1[3:])


index 3 to last:  [ 4  5  6  7  8  9 10 11 12]
index 3 to last:  [ 4  5  6  7  8  9 10 11 12]


In [51]:
# from istart to second to the last value
# index -1 equal last index.
print('index 3 to second to the last: ', a1[3:-1])


index 3 to second to the last:  [ 4  5  6  7  8  9 10 11]


In [52]:
print('last 2 numbers: ', a1[10:])
print('last 2 numbers: ', a1[-2:])


last 2 numbers:  [11 12]
last 2 numbers:  [11 12]


In [114]:
# get odd positions
# a1[istart : istop : istep]
print('odd positions: ', a1[0::2])


odd positions:  [ 1  3  5  7  9 11]


In [54]:
print('even positions: ', a1[1::2])


even positions:  [ 2  4  6  8 10 12]


In [55]:
import numpy as np

N = 12
a1 = np.arange(N+1)

array_properties(a1)


a = 
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12]
dim =  1
shape =  (13,)
datatype =  int32
size =  13



Use for loop on array.

In [56]:

for i in range(N+1):
    print(f'{i}: {a1[i]}')

0: 0
1: 1
2: 2
3: 3
4: 4
5: 5
6: 6
7: 7
8: 8
9: 9
10: 10
11: 11
12: 12


# Assignment

1. Create an array of shape (10, 10) with uint8 random values.
2. print the shape, size and dimension, 
3. Compute the sum of the third row to the last.
4. Compute the average of the columns


### 2 D Array


In [14]:
import numpy as np

a14 = np.arange(14+1)
print('size of a14=', a14.size)

if (a14.size % 4) == 0:
    reshape_a = a14.reshape((4,-1))
    print(reshape_a.shape)

size of a14= 15


In [13]:
# divide result in float
print('16 / 3=', 16 / 3)
# remainder 
print('16 % 3=', 16 % 3)
# whole or integer
print('16 // 3', 16 // 3, sep='=')

print('16 / 4=', 16 / 4)
print('16 % 4=', 16 % 4)
print('16 // 4=', 16 // 4)


16 / 3= 5.333333333333333
16 % 3= 1
16 // 3=5
16 / 4= 4.0
16 % 4= 0
16 // 4= 4


In [15]:
import numpy as np

a1 = np.arange(1, 17)

a2 = np.resize(a1, (4,4))
array_properties(a2)


a = 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
dim =  2
shape =  (4, 4)
datatype =  int32
size =  16



In [16]:
print('Element in row=1, column=1: ', a2[0,0])
print('Element in row=3, column=1: ', a2[2,0])
print('Element in row=2, column=3: ', a2[1,2])


Element in row=1, column=1:  1
Element in row=3, column=1:  9
Element in row=2, column=3:  7


In [21]:
array_properties(a2)

# row & index
row = 1
i = row - 1
# column & index
col = 2
j = col - 1

print(f'Element in row={row}, column={col}: {a2[i,j]}')


a = 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
dim =  2
shape =  (4, 4)
datatype =  int32
size =  16

Element in row=1, column=2: 2


In [22]:
# get all elements in row 2
print(f'Elements in row= 2: {a2[1,:]}')


Elements in row= 2: [5 6 7 8]


In [23]:
# alternative: get all elements in row 2 or dimension 1
print(f'Elements in row= 2: {a2[1]}')


Elements in row= 2: [5 6 7 8]


In [25]:
# get all value in column 2 or dimension
print('Elements in col= 2: ', a2[:,1])


Elements in col= 2:  [ 2  6 10 14]


In [28]:
# alternative: wrong get all value in column 2 or dimension 2
print('Elements in col= 2: ', a2[,1])


SyntaxError: invalid syntax (Temp/ipykernel_13660/1118262007.py, line 2)

In [62]:
print(f'Elements in rows= 1 to 3 and columns= 2 to 4: \n', a2[0:3,1:3])
print()
print(f'Elements in row index= 0 to 2 and column index= 1 to 2: \n', a2[0:3,1:3])


Elements in rows= 1 to 3 and columns= 2 to 4: 
 [[ 2  3]
 [ 6  7]
 [10 11]]

Elements in row index= 0 to 2 and column index= 1 to 2: 
 [[ 2  3]
 [ 6  7]
 [10 11]]


In [63]:
array_properties(a2)

rows, columns = a2.shape
for i in range(rows):
    for j in range(columns):
        print(f'{i},{j}: {a2[i,j]}', end=', ')
    print()

print()

rows, columns = a2.shape
for i in range(rows):
    for j in range(columns):
        print(a2[i,j], end=', ')
    print()

a = 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
dim =  2
shape =  (4, 4)
datatype =  int32
size =  16

0,0: 1, 0,1: 2, 0,2: 3, 0,3: 4, 
1,0: 5, 1,1: 6, 1,2: 7, 1,3: 8, 
2,0: 9, 2,1: 10, 2,2: 11, 2,3: 12, 
3,0: 13, 3,1: 14, 3,2: 15, 3,3: 16, 

1, 2, 3, 4, 
5, 6, 7, 8, 
9, 10, 11, 12, 
13, 14, 15, 16, 


### 3D Array

In [30]:
import numpy as np

a3 = np.arange(1, 9).reshape((2,2,2))
array_properties(a3)


a = 
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
dim =  3
shape =  (2, 2, 2)
datatype =  int32
size =  8



In [32]:

print(a3[0,1,1])
# 
print(a3[0,1,:])
print(a3[0,1])
# 
print(a3[0,:,1])
print(a3[:,1,1])


4
[3 4]
[3 4]
[2 4]
[4 8]


In [66]:

a3D = np.array([
    [
        [111,112,113],
        [121,122,123],
    ],
    [
        [211,212,213],
        [221,222,223],
    ]
])

array_properties(a3D)


a = 
 [[[111 112 113]
  [121 122 123]]

 [[211 212 213]
  [221 222 223]]]
dim =  3
shape =  (2, 2, 3)
datatype =  int32
size =  12



In [67]:
print('Element 1,2,2: ', a3D[0,1,1])

Element 1,2,2:  122


In [68]:
array_properties(a3)

rows_3d, rows, columns = a3.shape
for i in range(rows_3d):
    for j in range(rows):
        for k in range(columns):
            print(f'{i},{j},{k}: {a3[i,j,k]}', end=', ')
        print()
    print()

print()

rows_3d, rows, columns = a3.shape
for i in range(rows_3d):
    for j in range(rows):
        for k in range(columns):
            print(a3[i,j,k], end=', ')
        print()
    print()

a = 
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
dim =  3
shape =  (2, 2, 2)
datatype =  int32
size =  8

0,0,0: 1, 0,0,1: 2, 
0,1,0: 3, 0,1,1: 4, 

1,0,0: 5, 1,0,1: 6, 
1,1,0: 7, 1,1,1: 8, 


1, 2, 
3, 4, 

5, 6, 
7, 8, 



## Changing Array Element

In [33]:
import numpy as np

a3x3 = np.arange(1,10).reshape((3,-1))

print(a3x3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


||0|1|2|
|---|---|---|--|
|0|1|2|3|
|1|4|5|6|
|2|7|8|9|

In [34]:
# print value 6
print(a3x3[1,2])

6


In [38]:
# print 3
print(a3x3[0,2])

# change 3 to 33
a3x3[0,2] = 33

print(a3x3)

3
[[ 1  2 33]
 [ 4  5  6]
 [ 7 18  9]]


||0|1|2|
|---|---|---|--|
|0|1|2|33|
|1|4|5|6|
|2|7|8|9|

In [36]:
# change value 8 to 18
print(a3x3[2,1])
a3x3[2,1] = 18

print(a3x3)


8
[[ 1  2  3]
 [ 4  5  6]
 [ 7 18  9]]


In [39]:
import numpy as np

a1 = np.arange(9)
array_properties(a1)


print('Third element: ', a1[2])

a1[2] = a1[2] ** 2
print('Third element squared: ', a1[2])


a = 
 [0 1 2 3 4 5 6 7 8]
dim =  1
shape =  (9,)
datatype =  int32
size =  9

Third element:  2
Third element squared:  4


||0|1|2|3|4|5|6|7|8|
|---|---|---|---|---|---|---|---|---|---|
|0|0|1|2|3|4|5|6|7|8|

In [40]:
# 3 ^ 2 = 9

3 ** 2

9

In [43]:
import numpy as np

a2 = np.arange(1,10).reshape(3,3)
array_properties(a2)


print('2nd row, 2nd column element: ', a2[1,1])
a2[1,1] = a2[1,1] ** 2
print('2nd row, 2nd column element squared: ', a2[1,1])

print(a2)


a = 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
dim =  2
shape =  (3, 3)
datatype =  int32
size =  9

2nd row, 2nd column element:  5
2nd row, 2nd column element squared:  25
[[ 1  2  3]
 [ 4 25  6]
 [ 7  8  9]]


In [44]:

print('Third row: ', a2[2,:])
a2[2] = a2[2,:] * 2
print('Third row doubled: ', a2[2,:])

print(a2)


Third row:  [7 8 9]
Third row doubled:  [14 16 18]
[[ 1  2  3]
 [ 4 25  6]
 [14 16 18]]


In [45]:

print('First row: ', a2[0,:])
a2[0] = a2[0,:] + a2[1,:]
print('First row increased by second row: ', a2[0,:])

print(a2)


First row:  [1 2 3]
First row increased by second row:  [ 5 27  9]
[[ 5 27  9]
 [ 4 25  6]
 [14 16 18]]


In [46]:

print('Second row: ', a2[1,:])
a2[1] = a2[1,:] - a2[2,:]
print('Second row decreased by third row: ', a2[1,:])

print(a2)


Second row:  [ 4 25  6]
Second row decreased by third row:  [-10   9 -12]
[[  5  27   9]
 [-10   9 -12]
 [ 14  16  18]]


In [42]:
x = 3
y=4
print('x=', x, 'y=', y)
x = x - y
print('x=', x, 'y=', y)



x= 3 y= 4
x= -1 y= 4


## Class Activity

1. Create an array a of shape (2, 5) and another array b of shape (3, 5).
2. Create another array c = a
3. Change array c row 2 to the sum of array a row 2 and array b row 2.