# Chapter 8 


In [2]:
!pip install -q numpy 

In [3]:
def array_properties(a, label='a'):
    print(label, '= ')
    print(a)
    print("dim = ", a.ndim)
    print("shape = ", a.shape)
    print("datatype = ", a.dtype)
    print("size = ", a.size)
    print()

# Linear Algebra 1 


## Creating a matrix representation of sytem linear equation


$$
A . x = b
$$

$$
x = \frac {b} {A}
$$

$$
x = A^{-1} . b
$$

$$
3x_1 -3x_2 - 4x_3 = 1 \\
x_1 - x_2 - x_3 = 2 \\
2x_1 - x_2 + 4x_3 = 3	
$$



$$
A=\left(
        \begin{matrix} 
            3 & -3 & -4 \\ 
            1 & -1 & -1 \\ 
            2 & -1 & 4 \\ 
        \end{matrix}
    \right)
$$

$$
x=\left(
        \begin{matrix} 
            x_1 \\ 
            x_2 \\ 
            x_3 \\ 
        \end{matrix}
    \right)
$$

$$
b=\left(
        \begin{matrix} 
            1 \\ 
            2 \\ 
            3 \\ 
        \end{matrix}
    \right)
$$

In [4]:
import numpy as np

A = np.array([
    [3, -3, -4],
    [1, -1, -1],
    [2, -1, 4],
])

array_properties(A, 'A')


A = 
[[ 3 -3 -4]
 [ 1 -1 -1]
 [ 2 -1  4]]
dim =  2
shape =  (3, 3)
datatype =  int32
size =  9



In [5]:
import numpy as np

b = np.array([
    [1],
    [2],
    [3],
])

array_properties(b, 'b')


b = 
[[1]
 [2]
 [3]]
dim =  2
shape =  (3, 1)
datatype =  int32
size =  3



## Vector, Matrix or Tensor Order

The order of a vector or matrix or tensor is the shape.

For vector or matrix it is in form of $m \times n$ , that is, $\text{number of rows} \times \text{number of columns}$

$$
A=\left(
        \begin{matrix} 
            3 & -3 & -4 \\ 
            1 & -1 & -1 \\ 
            2 & -1 & 4 \\ 
        \end{matrix}
    \right)
    = 3 \times 3
$$

$$
x=\left(
        \begin{matrix} 
            x_1 \\ 
            x_2 \\ 
            x_3 \\ 
        \end{matrix}
    \right)
    = 3 \times 1
$$

$$
b=\left(
        \begin{matrix} 
            1 \\ 
            2 \\ 
            3 \\ 
        \end{matrix}
    \right)
    = 3 \times 1

$$

## Matrix Operation

$$
A + B = B + A \\ 
A=m_a \times n_a , \quad B = m_b \times n_b  \\ 
\text{if and only if:} \quad m_a = m_b, \quad n_a = n_b
$$



$$
A - B = -(B - A) \\ 
A=m_a \times n_a , \quad B = m_b \times n_b  \\ 
\text{if and only if:} \quad m_a = m_b, \quad n_a = n_b
$$



$$
A \times B = C \\ 
A=m_a \times n_a , \quad B = m_b \times n_b   \\ 
\text{if and only if:} \quad n_a = m_b \\ 
\text{then} \\ 
C = m_c \times n_c \\ 
m_c = m_a \quad n_c = n_b
$$

## Class Activity

1. Create two (2) matrices of $4 \times 4$ order and carryout above matrix operation.

### Transpose

In [7]:
import numpy as np

transpose_A = np.transpose(A)

array_properties(A, 'A')

array_properties(transpose_A, 'transpose of A')

A = 
[[ 3 -3 -4]
 [ 1 -1 -1]
 [ 2 -1  4]]
dim =  2
shape =  (3, 3)
datatype =  int32
size =  9

transpose of A = 
[[ 3  1  2]
 [-3 -1 -1]
 [-4 -1  4]]
dim =  2
shape =  (3, 3)
datatype =  int32
size =  9



In [8]:
import numpy as np

transpose_b = np.transpose(b)

array_properties(b, 'b')

array_properties(transpose_b, 'transpose of b')

b = 
[[1]
 [2]
 [3]]
dim =  2
shape =  (3, 1)
datatype =  int32
size =  3

transpose of b = 
[[1 2 3]]
dim =  2
shape =  (1, 3)
datatype =  int32
size =  3

