# Chapter 8 


In [1]:
!pip install -q numpy 

You should consider upgrading via the 'c:\program files (x86)\microsoft visual studio\shared\python39_64\python.exe -m pip install --upgrade pip' command.


In [2]:
def array_properties(a, label='a'):
    print(label, '= ')
    print(a)
    print("dim = ", a.ndim)
    print("shape = ", a.shape)
    print("datatype = ", a.dtype)
    print("size = ", a.size)
    print()

# Linear Algebra 1 


## Creating a matrix representation of sytem linear equation


$$
A.x=b 
$$

$$
a_{1,1}x_1 + a_{1,2}x_2 + a_{1,3}x_3 + ... + a_{1,n-1}x_{n-1} + a_{1,n}x_n = b_1  \\ 
a_{2,1}x_1 + a_{2,2}x_2 + a_{2,3}x_3 + ... + a_{2,n-1}x_{n-1} + a_{2,n}x_n = b_2  \\
... \\ 
a_{m,1}x_1 + a_{m,2}x_2 + a_{m,3}x_3 + ... + a_{m,n-1}x_{n-1} + a_{m,n}x_n = b_m
$$

Check the system of linear equation below:

1. How many variables? 
   1. 4
   2. $x_1, \quad x_2, \quad  x_3 \quad and \quad x_4$
2. How many coefficients of $x_1$
   1. 4
   2. $11, \quad  21, \quad 31, \quad and 41$
3. What are the coeffiecient of $x_4$
   1. $-14, \quad  -24, \quad  -34, \quad  -44$
4. What will be the order (shape) of $A$ the coeffiecients of $x(s)$
   1. 4x4   
5. What is the order (shape) of x
   1. 4x1
6. What is the order of b
   1. 4x1
7. 

$$ 
11x_1 + 12x_2 + 13x_3 - 14x_4 = 1 \\ 
21x_1 + 22x_2 + 23x_3 - 24x_4 = 2 \\ 
31x_1 + 32x_2 + 33x_3 - 34x_4 = 3 \\ 
41x_1 + 42x_2 + 43x_3 - 44x_4 = 4 \\ 
$$ 

$$

\begin{bmatrix}
    11 & 12 & 13 & -14 \\ 
    21 & 22 & 23 & -24 \\ 
    31 & 32 & 33 & -34 \\ 
    41 & 42 & 43 & -44 \\ 
\end{bmatrix}

\begin{bmatrix}
    x_1 \\ 
    x_2 \\ 
    x_3 \\ 
    x_4 \\ 
\end{bmatrix}

=
\begin{bmatrix}
    b_1 \\ 
    b_2 \\ 
    b_3 \\ 
    b_4 \\ 
\end{bmatrix}

$$

$$
4 \times 4 \quad 4 \times 1 = 4 \times 1
$$

## Class Activity

Create the array of the system of equation above for A and b

In [9]:
import numpy as np

# create A
A = np.array([
    [11, 12, 13, -14],
    [21, 22, 23, -24],
    [31, 32, 33, -34],
    [41, 42, 43, -44],
])

array_properties(A, 'A')

# create b
b = np.array([
    [1],
    [2],
    [3],
    [4],
])

array_properties(b, 'b')


A = 
[[ 11  12  13 -14]
 [ 21  22  23 -24]
 [ 31  32  33 -34]
 [ 41  42  43 -44]]
dim =  2
shape =  (4, 4)
datatype =  int32
size =  16

b = 
[[1]
 [2]
 [3]
 [4]]
dim =  2
shape =  (4, 1)
datatype =  int32
size =  4



In [7]:
import numpy as np

# create A
A = np.array([
    [
        [11, 12, 13, -14],
        [21, 22, 23, -24],
        [31, 32, 33, -34],
        [41, 42, 43, -44],
    ]
])

array_properties(A)

AA = np.squeeze(A)
array_properties(AA)

AAA = np.squeeze(AA)
print('AAA shape: ', AAA.shape)

a = 
[[[ 11  12  13 -14]
  [ 21  22  23 -24]
  [ 31  32  33 -34]
  [ 41  42  43 -44]]]
dim =  3
shape =  (1, 4, 4)
datatype =  int32
size =  16

a = 
[[ 11  12  13 -14]
 [ 21  22  23 -24]
 [ 31  32  33 -34]
 [ 41  42  43 -44]]
dim =  2
shape =  (4, 4)
datatype =  int32
size =  16

AAA shape:  (4, 4)


In [12]:
# alternative to creation of array b

b = np.array([1,2,3,4])
array_properties(b, 'b')

# transpose of 1 dimension 
# fails to convert to 2 dimension
bT = np.transpose(b)
array_properties(bT, 'bT')

# reshape
bb = b.reshape((4,1))
array_properties(bb, 'bb')




b = 
[1 2 3 4]
dim =  1
shape =  (4,)
datatype =  int32
size =  4

bT = 
[1 2 3 4]
dim =  1
shape =  (4,)
datatype =  int32
size =  4

bb = 
[[1]
 [2]
 [3]
 [4]]
dim =  2
shape =  (4, 1)
datatype =  int32
size =  4



In [14]:
print('b[0]=', b[0])
print('bb[0]=', bb[0])


b[0]= 1
bb[0]= [1]


## Solution to system of linear equation
### Theory  
$$
A.x=b
$$

$$
x = \frac {b} {A}
$$

$$
x = A^{-1} . b
$$

## Example
Solve the system of linear equation below:
$$
3x_1 - 3x_2 - 4x_3 = 1  \\  
x_1 - x_2 - x_3 = 2  \\  
2x_1 - x_2 + 4x_3 = 3  \\  
$$

In [15]:
import numpy as np

A = np.array([
    [3, -3, -4],
    [1, -1, -1],
    [2, -1, 4],
])

array_properties(A, 'A')


A = 
[[ 3 -3 -4]
 [ 1 -1 -1]
 [ 2 -1  4]]
dim =  2
shape =  (3, 3)
datatype =  int32
size =  9



In [16]:
import numpy as np

b = np.array([
    [1],
    [2],
    [3],
])

array_properties(b, 'b')


b = 
[[1]
 [2]
 [3]]
dim =  2
shape =  (3, 1)
datatype =  int32
size =  3



In [17]:
import numpy as np

x = np.linalg.solve(A, b)

array_properties(x, 'x')

x = 
[[-24.]
 [-31.]
 [  5.]]
dim =  2
shape =  (3, 1)
datatype =  float64
size =  3



## Class Activity

Check if the solution above is correct, using the second equation of the ssytem of linear equations.

$$
3x_1 - 3x_2 - 4x_3 = 1  \\  
x_1 - x_2 - x_3 = 2  \\  
2x_1 - x_2 + 4x_3 = 3  \\  
$$

### alternative solution

$$
A.x=b
$$

$$
x = \frac {b} {A}
$$

$$
x = A^{-1} . b
$$

In [26]:
# using inverse of A

from numpy import linalg

A = np.array([
    [3, -3, -4],
    [1, -1, -1],
    [2, -1, 4],
])

b = np.array([
    [1],
    [2],
    [3],
])

# get inverse of A
inv_of_A = linalg.inv(A)

array_properties(inv_of_A, 'inv_of_A')

# A^-1 * b
x = inv_of_A @ b

array_properties(x, 'x')



inv_of_A = 
[[  5. -16.   1.]
 [  6. -20.   1.]
 [ -1.   3.   0.]]
dim =  2
shape =  (3, 3)
datatype =  float64
size =  9

x = 
[[-24.]
 [-31.]
 [  5.]]
dim =  2
shape =  (3, 1)
datatype =  float64
size =  3



In [27]:
# A^-1 * b
x1 = inv_of_A.dot(b)

array_properties(x1, 'x1')

x == x1

x1 = 
[[-24.]
 [-31.]
 [  5.]]
dim =  2
shape =  (3, 1)
datatype =  float64
size =  3



array([[ True],
       [ True],
       [ True]])

In [29]:
# A^-1 * b
x2 = np.linalg.multi_dot([inv_of_A, b])

array_properties(x2, 'x2')

x == x2

x2 = 
[[-24.]
 [-31.]
 [  5.]]
dim =  2
shape =  (3, 1)
datatype =  float64
size =  3



array([[ True],
       [ True],
       [ True]])

## Crammer's Rule or Determinant method

$$
x_i = \frac {D_i} {D}   

$$

where $D$ is the determinant of matrix $A$ and $D_i$ is the determinant of matrix $A_i$.  
Matrix $A_i$ is matrix $A$ where the column $i$ is replaced with matrix $b$  

$$
a_{11} x_1 + a_{12} x_2 + a_{13} x_3 = b_1  \\  
a_{21} x_1 + a_{22} x_2 + a_{23} x_3 = b_2  \\  
a_{31} x_1 + a_{32} x_2 + a_{33} x_3 = b_3  \\  
$$

$$
A = 
\begin{bmatrix}
    a_{11} & a_{11} & a_{11}  \\ 
    a_{21} & a_{21} & a_{21}  \\ 
    a_{31} & a_{31} & a_{31}  \\ 
\end{bmatrix}
, \quad  

b = \begin{bmatrix}
    b_1 \\
    b_2 \\
    b_3 \\
\end{bmatrix}
$$

$$
A_1 = 
\begin{bmatrix}
    b_1 & a_{11} & a_{11}  \\ 
    b_2 & a_{21} & a_{21}  \\ 
    b_3 & a_{31} & a_{31}  \\ 
\end{bmatrix}
, \quad  
A_2 = 
\begin{bmatrix}
    a_{11} & b_{1} & a_{11}  \\ 
    a_{21} & b_{2} & a_{21}  \\ 
    a_{31} & b_{3} & a_{31}  \\ 
\end{bmatrix}
, \quad  
A_3 = 
\begin{bmatrix}
    a_{11} & a_{11} & b_{1}  \\ 
    a_{21} & a_{21} & b_{2}  \\ 
    a_{31} & a_{31} & b_{3}  \\ 
\end{bmatrix}
$$

In [32]:
# crammer's rule or determinant method

# importing only determinant from linalg module
from numpy.linalg import det

# create array A and b
A = np.array([
    [3, -3, -4],
    [1, -1, -1],
    [2, -1, 4],
])

b = np.array([
    [1],
    [2],
    [3],
])

# find determinant of A
D = det(A)
print('D=', D)

D= -0.9999999999999998


## Class Activity

Create array A1, A2 and A3 from the theory discussed earlier for crammer's rule or determinant method.

In [35]:
# crammer's rule or determinant method

# importing only determinant from linalg module
from numpy.linalg import det

# create array A and b
A = np.array([
    [3, -3, -4],
    [1, -1, -1],
    [2, -1, 4],
])

b = np.array([
    [1],
    [2],
    [3],
])

# create empty x
x = np.empty((3,1))

# find determinant of A
D = det(A)
print('D=', D)

(m,n) = A.shape

A_list = []
Di_list = []

for i in range(n):
    # get Ai
    # copy original array
    Ai = A.copy()
    # replace column i in the new array with b
    Ai[:,i] = b[:,0]
    # store new array Ai in a list
    A_list.insert(i, Ai)
    # find determinant of Ai 
    Di = det(Ai)
    # store Di
    Di_list.insert(i,Di)
    # compute xi
    x[i] = Di / D 


array_properties(x, 'x')

print('A_list', A_list)
print('Di_list', Di_list)



D= -0.9999999999999998
x = 
[[-24.]
 [-31.]
 [  5.]]
dim =  2
shape =  (3, 1)
datatype =  float64
size =  3

A_list [array([[ 1, -3, -4],
       [ 2, -1, -1],
       [ 3, -1,  4]]), array([[ 3,  1, -4],
       [ 1,  2, -1],
       [ 2,  3,  4]]), array([[ 3, -3,  1],
       [ 1, -1,  2],
       [ 2, -1,  3]])]
Di_list [24.000000000000014, 31.0, -5.000000000000001]


## Vector, Matrix or Tensor Order

The order of a vector or matrix or tensor is the shape.

For vector or matrix it is in form of $m \times n$ , that is, $\text{number of rows} \times \text{number of columns}$

$$
A=\left(
        \begin{matrix} 
            3 & -3 & -4 \\ 
            1 & -1 & -1 \\ 
            2 & -1 & 4 \\ 
        \end{matrix}
    \right)
    = 3 \times 3
$$

$$
x=\left(
        \begin{matrix} 
            x_1 \\ 
            x_2 \\ 
            x_3 \\ 
        \end{matrix}
    \right)
    = 3 \times 1
$$

$$
b=\left(
        \begin{matrix} 
            1 \\ 
            2 \\ 
            3 \\ 
        \end{matrix}
    \right)
    = 3 \times 1

$$

## Matrix Operation

$$
A + B = B + A \\ 
A=m_a \times n_a , \quad B = m_b \times n_b  \\ 
\text{if and only if:} \quad m_a = m_b, \quad n_a = n_b
$$



$$
A - B = -(B - A) \\ 
A=m_a \times n_a , \quad B = m_b \times n_b  \\ 
\text{if and only if:} \quad m_a = m_b, \quad n_a = n_b
$$



$$
A \times B = C \\ 
A=m_a \times n_a , \quad B = m_b \times n_b   \\ 
\text{if and only if:} \quad n_a = m_b \\ 
\text{then} \\ 
C = m_c \times n_c \\ 
m_c = m_a \quad n_c = n_b
$$

## Class Activity

1. Create two (2) matrices of $4 \times 4$ order and carryout above matrix operation.

In [36]:
from numpy import random

A = random.randint(0,10,(4,4))
B = random.randint(0,10,(4,4))

array_properties(A, 'A')
array_properties(B, 'B')


A = 
[[7 2 8 4]
 [8 4 7 4]
 [1 7 2 9]
 [9 7 8 1]]
dim =  2
shape =  (4, 4)
datatype =  int32
size =  16

B = 
[[7 8 7 5]
 [5 0 8 7]
 [8 6 0 6]
 [9 2 8 2]]
dim =  2
shape =  (4, 4)
datatype =  int32
size =  16



In [37]:

C = A + B
array_properties(C, 'C')

C1 = B + A
array_properties(C1, 'C1')

C == C1


C = 
[[14 10 15  9]
 [13  4 15 11]
 [ 9 13  2 15]
 [18  9 16  3]]
dim =  2
shape =  (4, 4)
datatype =  int32
size =  16

C1 = 
[[14 10 15  9]
 [13  4 15 11]
 [ 9 13  2 15]
 [18  9 16  3]]
dim =  2
shape =  (4, 4)
datatype =  int32
size =  16



array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [38]:

C = A - B
array_properties(C, 'C')

C1 = B - A
array_properties(C1, 'C1')

C == C1


C = 
[[ 0 -6  1 -1]
 [ 3  4 -1 -3]
 [-7  1  2  3]
 [ 0  5  0 -1]]
dim =  2
shape =  (4, 4)
datatype =  int32
size =  16

C1 = 
[[ 0  6 -1  1]
 [-3 -4  1  3]
 [ 7 -1 -2 -3]
 [ 0 -5  0  1]]
dim =  2
shape =  (4, 4)
datatype =  int32
size =  16



array([[ True, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [ True, False,  True, False]])

In [39]:

C = A * B
array_properties(C, 'C')

C1 = B * A
array_properties(C1, 'C1')

C == C1


C = 
[[49 16 56 20]
 [40  0 56 28]
 [ 8 42  0 54]
 [81 14 64  2]]
dim =  2
shape =  (4, 4)
datatype =  int32
size =  16

C1 = 
[[49 16 56 20]
 [40  0 56 28]
 [ 8 42  0 54]
 [81 14 64  2]]
dim =  2
shape =  (4, 4)
datatype =  int32
size =  16



array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [40]:

C = A @ B
array_properties(C, 'C')

C1 = B @ A
array_properties(C1, 'C1')

C == C1


C = 
[[159 112  97 105]
 [168 114 120 118]
 [139  38 135  84]
 [171 122 127 144]]
dim =  2
shape =  (4, 4)
datatype =  int32
size =  16

C1 = 
[[165 130 166 128]
 [106 115 112  99]
 [158  82 154  62]
 [105  96 118 118]]
dim =  2
shape =  (4, 4)
datatype =  int32
size =  16



array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

### Transpose

In [41]:
import numpy as np

A = np.arange(1,10).reshape(3,3)

transpose_A = np.transpose(A)

array_properties(A, 'A')

array_properties(transpose_A, 'transpose of A')

A = 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
dim =  2
shape =  (3, 3)
datatype =  int32
size =  9

transpose of A = 
[[1 4 7]
 [2 5 8]
 [3 6 9]]
dim =  2
shape =  (3, 3)
datatype =  int32
size =  9



In [42]:
import numpy as np

transpose_b = np.transpose(b)

array_properties(b, 'b')

array_properties(transpose_b, 'transpose of b')

b = 
[[1]
 [2]
 [3]]
dim =  2
shape =  (3, 1)
datatype =  int32
size =  3

transpose of b = 
[[1 2 3]]
dim =  2
shape =  (1, 3)
datatype =  int32
size =  3



## Class Activity

1. Create array A and make a transposed copy as B.
2. Carryout 
   1. A + B == B + A 
   2. A - B == -(B - A) 
   3. A * B == B + A 
   4. A @ B == B @ A
      

In [43]:
import numpy as np

A = np.arange(1,10).reshape(3,3)

B = np.transpose(A.copy())

array_properties(A, 'A')
array_properties(B, 'B')




A = 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
dim =  2
shape =  (3, 3)
datatype =  int32
size =  9

B = 
[[1 4 7]
 [2 5 8]
 [3 6 9]]
dim =  2
shape =  (3, 3)
datatype =  int32
size =  9



In [44]:
C = A + B
C1 = B + A

array_properties(C, 'C')
array_properties(C1, 'C1')

C == C1

C = 
[[ 2  6 10]
 [ 6 10 14]
 [10 14 18]]
dim =  2
shape =  (3, 3)
datatype =  int32
size =  9

C1 = 
[[ 2  6 10]
 [ 6 10 14]
 [10 14 18]]
dim =  2
shape =  (3, 3)
datatype =  int32
size =  9



array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [46]:
C = A - B
C1 = B - A

array_properties(C, 'C')
array_properties(C1, 'C1')

C == -C1

C = 
[[ 0 -2 -4]
 [ 2  0 -2]
 [ 4  2  0]]
dim =  2
shape =  (3, 3)
datatype =  int32
size =  9

C1 = 
[[ 0  2  4]
 [-2  0  2]
 [-4 -2  0]]
dim =  2
shape =  (3, 3)
datatype =  int32
size =  9



array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [47]:
C = A * B
C1 = B * A

array_properties(C, 'C')
array_properties(C1, 'C1')

C == C1

C = 
[[ 1  8 21]
 [ 8 25 48]
 [21 48 81]]
dim =  2
shape =  (3, 3)
datatype =  int32
size =  9

C1 = 
[[ 1  8 21]
 [ 8 25 48]
 [21 48 81]]
dim =  2
shape =  (3, 3)
datatype =  int32
size =  9



array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [48]:
C = A @ B
C1 = B @ A

array_properties(C, 'C')
array_properties(C1, 'C1')

C == C1

C = 
[[ 14  32  50]
 [ 32  77 122]
 [ 50 122 194]]
dim =  2
shape =  (3, 3)
datatype =  int32
size =  9

C1 = 
[[ 66  78  90]
 [ 78  93 108]
 [ 90 108 126]]
dim =  2
shape =  (3, 3)
datatype =  int32
size =  9



array([[False, False, False],
       [False, False, False],
       [False, False, False]])

## Identity Matrix or Array

In [49]:
import numpy as np

a = np.array([
    [1,0],
    [0,1],
])

array_properties(a)

a = 
[[1 0]
 [0 1]]
dim =  2
shape =  (2, 2)
datatype =  int32
size =  4



In [50]:
import numpy as np

a1 = np.array([
    [1,2],
    [3,4],
])

array_properties(a1)

a = 
[[1 2]
 [3 4]]
dim =  2
shape =  (2, 2)
datatype =  int32
size =  4



In [51]:
a * a1

array([[1, 0],
       [0, 4]])

In [52]:
a @ a1

array([[1, 2],
       [3, 4]])

In [53]:
import numpy as np

A = np.arange(1,10).reshape(3,3)

B = np.transpose(A.copy())

array_properties(A, 'A')
array_properties(B, 'B')

A = 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
dim =  2
shape =  (3, 3)
datatype =  int32
size =  9

B = 
[[1 4 7]
 [2 5 8]
 [3 6 9]]
dim =  2
shape =  (3, 3)
datatype =  int32
size =  9



In [54]:
# get shape of A
M,N = A.shape

# create identity matrix of shape A
I = np.eye(N)

array_properties(I, 'I')

I = 
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
dim =  2
shape =  (3, 3)
datatype =  float64
size =  9



In [55]:
A @ B

array([[ 14,  32,  50],
       [ 32,  77, 122],
       [ 50, 122, 194]])

In [56]:
B @ A

array([[ 66,  78,  90],
       [ 78,  93, 108],
       [ 90, 108, 126]])

In [57]:
A @ B == B @ A

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [58]:
A @ I

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [59]:
I @ A

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [60]:
A @ I == I @ A

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

# Assigmnent

1. Create a random array a, of shape (6x6) using randint and seed 2.
2. Convert the array a, to an identity matrix I. 


$$
I = 
\begin{bmatrix}
    1 & 0 & 0 & 0 & 0 & 0  \\  
    0 & 1 & 0 & 0 & 0 & 0  \\  
    0 & 0 & 1 & 0 & 0 & 0  \\  
    0 & 0 & 0 & 1 & 0 & 0  \\  
    0 & 0 & 0 & 0 & 1 & 0  \\  
    0 & 0 & 0 & 0 & 0 & 1  \\  
\end{bmatrix}
$$