# Chapter 9 



In [3]:
!pip install -q numpy 

In [2]:
def array_properties(a, label='a'):
    print(label, '= ')
    print(a)
    print("dim = ", a.ndim)
    print("shape = ", a.shape)
    print("datatype = ", a.dtype)
    print("size = ", a.size)
    print()

# Linear Algebra 2 


## Creating a matrix representation of system of linear equation



$$
A . x = b
$$

$$
x = \frac {b} {A}
$$

$$
x = A^{-1} . b
$$

$$
3x_1 -3x_2 - 4x_3 = 1 \\
x_1 - x_2 - x_3 = 2 \\
2x_1 - x_2 + 4x_3 = 3	
$$



$$
A=\left(
        \begin{matrix} 
            3 & -3 & -4 \\ 
            1 & -1 & -1 \\ 
            2 & -1 & 4 \\ 
        \end{matrix}
    \right)
$$

$$
x=\left(
        \begin{matrix} 
            x_1 \\ 
            x_2 \\ 
            x_3 \\ 
        \end{matrix}
    \right)
$$

$$
b=\left(
        \begin{matrix} 
            1 \\ 
            2 \\ 
            3 \\ 
        \end{matrix}
    \right)
$$

Solve for the values of $ x $.

In [7]:
import numpy as np

A = np.array([
    [3., -3., -4.],
    [1, -1, -1],
    [2, -1, 4],
])

array_properties(A, 'A')


A = 
[[ 3. -3. -4.]
 [ 1. -1. -1.]
 [ 2. -1.  4.]]
dim =  2
shape =  (3, 3)
datatype =  float64
size =  9



In [8]:
import numpy as np

b = np.array([
    [1.],
    [2],
    [3],
])

array_properties(b, 'b')


b = 
[[1.]
 [2.]
 [3.]]
dim =  2
shape =  (3, 1)
datatype =  float64
size =  3



In [9]:
import numpy as np

x = np.linalg.solve(A,b)

array_properties(x, 'x')

x = 
[[-24.]
 [-31.]
 [  5.]]
dim =  2
shape =  (3, 1)
datatype =  float64
size =  3



In [11]:
import numpy as np

A_inv = np.linalg.inv(A)

x = A_inv @ b

array_properties(A_inv, 'A_inv')
array_properties(x, 'x')


A_inv = 
[[  5. -16.   1.]
 [  6. -20.   1.]
 [ -1.   3.   0.]]
dim =  2
shape =  (3, 3)
datatype =  float64
size =  9

x = 
[[-24.]
 [-31.]
 [  5.]]
dim =  2
shape =  (3, 1)
datatype =  float64
size =  3



$$

x_1 = \frac {D_1} {D}

$$

In [21]:
D = np.linalg.det(A)
print('D = ', D)


D =  -0.9999999999999998


In [22]:
A1 = A.copy()


A1[:,0] = b[:,0]
array_properties(A1, 'A1')

D1 = np.linalg.det(A1)
print('D1= ', D1)

x1 = D1 / D
print('x1 = ', x1)

A1 = 
[[ 1. -3. -4.]
 [ 2. -1. -1.]
 [ 3. -1.  4.]]
dim =  2
shape =  (3, 3)
datatype =  float64
size =  9

D1=  24.000000000000014
x1 =  -24.00000000000002


In [24]:
# xx = []

for i in range(3):
    AA = A.copy()

    AA[:,i] = b[:,0]
    # array_properties(AA, f'A{i+1}')

    DD = np.linalg.det(AA)
    print(f'D{i+1}= ', DD)

    xx = DD / D
    print(f'x{i+1} = ', xx)


D1=  24.000000000000014
x1 =  -24.00000000000002
D2=  31.0
x2 =  -31.000000000000007
D3=  -5.000000000000001
x3 =  5.000000000000002
