# Assignment

1. Create an array of shape (10, 10) with uint8 random values.
2. print the shape, size and dimension, 
3. Compute the sum of the third row to the last.
4. Compute the average of the columns


In [18]:
# 1. Create an array of shape (10, 10) with uint8 random values.

import numpy as np

ar10x10 = np.random.randint(0, 256, (10,10), dtype='uint8') 
# ar10x10 = np.random.randint(0, 256, (10,10), dtype=np.uint8) 


In [19]:
# 2. print the shape, size and dimension, 

print('shape=', ar10x10.shape)
print('size=', ar10x10.size)
print('dimension=', ar10x10.ndim)


shape= (10, 10)
size= 100
dimension= 2


In [5]:
row_3_from_last = ar10x10[-3]
print(row_3_from_last)

[203  66   9   5 135 255 206 122  69 212]


In [10]:
sum_row_3_from_last = np.sum(row_3_from_last)
print(sum_row_3_from_last)

1282


In [21]:
# 3. Compute the sum of the third row to the last.

row_3_to_last = ar10x10[3:]
print(row_3_to_last)


sum_row_3_to_last = np.sum(row_3_to_last)
print('sum=', sum_row_3_to_last)

[[213  84  84  89  67  70  78  29 168  33]
 [ 97  80 102 138  40 106  43  85 219   1]
 [134   9 227 109 180  10 146 249 179 137]
 [ 63 150 233 242 244  30 197 134 213  58]
 [ 16  59  37 184  86  82   1 120  64  23]
 [185  32  96 161   2  53 102 195  60 151]
 [101 154 232 205 123 228 230 176  16  32]]
sum= 7976


In [14]:
sum_row_3_to_last_axis_0 = np.sum(row_3_to_last, axis=0)
print(sum_row_3_to_last_axis_0)
sum_row_3_to_last_axis_0.shape

[ 918  592  689  623 1007  999 1072 1127  587 1199]


(10,)

In [15]:
sum_row_3_to_last_axis_1 = np.sum(row_3_to_last, axis=1)
print(sum_row_3_to_last_axis_1)
sum_row_3_to_last_axis_1.shape

[ 960 1297 1425 1414 1282 1088 1347]


(7,)

In [22]:
# 4. Compute the average of the columns

ar_ave = np.mean(ar10x10, axis=0)
print(ar_ave)

[124.1 104.7 144.7 140.7 106.7 105.6 119.9 143.6 141.3  82.2]
