In [1]:
import numpy as np

a = np.random.randint(0, 1000, (5,6))

print(a)

[[129 914 550 426 826 211]
 [374  91 205 357 912 419]
 [384 514 820 603 791 866]
 [264 527 861 530 975 876]
 [458 804 620 599 583 553]]
